name: Reminder on Push

on:
  push:    # whenever someone pushes (commits)

permissions:
  issues: write   # Needed to create an Issue

jobs:
  remind-committer:
    runs-on: ubuntu-latest

    steps:
      - name: Create Reminder Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 📢 Reminder:Push Carefully!
          content-file: .github/push-reminder.md
